### PR TITLE
bump eslint-plugin-github to v5.0.1

### PR DESCRIPTION
**Pull request by khiga8**
Bumps the dependency, `eslint-plugin-github`, to the latest major version which includes:

* [release notes v5.0.0](https://github.com/github/eslint-plugin-github/releases): drops support for node 14 and node 16 in favor of node 18.
* [release notes v5.0.1](https://github.com/github/eslint-plugin-github/releases/tag/v5.0.1) : changes to the recommended config for `no-redundant-roles`.

### CODE REVIEW

**Comment by khiga8** [comment]
Hey @joshblack! The main notable change is that we dropped support in `eslint-plugin-github` for node 14 and node 16 in favor of node 18.

I see that [ci.yml](https://github.com/primer/eslint-plugin-primer-react/blob/main/.github/workflows/ci.yml) is already running node 18 so I don't believe anything needs to change.

**Comment by joshblack** [comment]
@khiga8 ah thanks for explaining the node change. In this case, if someone is using `eslint-plugin-primer-react` and is using Node 14 or 16 then it would no longer work as expected? (Due to usage of ` eslint-plugin-github` and it no longer supporting these versions)

For context, I'm not looking at this from the perspective of someone using the package and if this would be a breaking change for them or not.

**Comment by khiga8** [comment]
Hey @joshblack! Thats a great question.. 👀 .

I dropped node 14 in `eslint-plugin-github` because I was running into issues with running tests specifically in a [node 14 test build](https://github.com/github/eslint-plugin-github/actions/runs/9117802749/job/25069494984). I reached out [on slack thread](https://github.slack.com/archives/CMZ4DC9BL/p1715889545220439?thread_ts=1715874890.704489&cid=CMZ4DC9BL), and it was pointed out that we generally only support Node LTS so it seemed reasonable to drop node 14/16. This seems to align with [how node 20 will soon be the the default in GitHub Actions](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/)

The SyntaxError we saw in node 14 seemed related to the library test setup, and not the actively shipped code. It is possible the plugin will continue to run as expected for consumers in Node 14/Node 16. However, because we formally dropped node 14 and node 16 from the library testing matrix, we won't be able to guarantee that the plugin will work so I decided to cut a major release version just in case!

If we merge this in, it could be a good idea to cut a major release to be safe, but I did notice that the [CI test matrix for `eslint-plugin-primer-react`](https://github.com/primer/eslint-plugin-primer-react/blob/main/.github/workflows/ci.yml) only runs node 18 anyways while the [CI test for `primer/react`](https://github.com/primer/react/blob/main/.github/workflows/ci.yml) only runs node 20. Does this mean that technically these libraries are already not formally supporting node <18 🤔 ? Curious to hear your thoughts!

**Review by joshblack — APPROVED** [review]
Thanks for taking the time to explain @khiga8! Would you mind including a changeset? Then should be good to go 💯

**Pull request merged**
