### PR TITLE
Add `explicit-heading` rule

### PR DESCRIPTION
**Pull request by TylerJDev**
Adds `explicit-heading` rule. This rule disallows the following: 

* Using `Heading` without providing a heading level via `as`, (e.g. `<Heading>`)
* Using `as` for any element that is not a heading (`h1`-`h6`)

Additional context: https://github.com/primer/eslint-plugin-primer-react/issues/57.

### CODE REVIEW

**Comment by khiga8** [comment]
I can review more carefully tomorrow, but do you think this is considered an accessibility rule, and would we want to include this rule in the accessibility scorecard? 

If so, we should prefix the name with `a11y-` which would allow us to flag it as an accessibility rule.

**Review by khiga8 — COMMENTED** [review]
I have one open question about prefixing this lint rule with `a11y-` so we can identify it as an accessibility-related rule more easily and eventualy track it in our scorecard. (We're still figuring out the rollout system around that in https://github.com/github/accessibility/issues/3868).


Aside from that, I have no concerns. This is awesome! 🎉

**Comment by TylerJDev** [comment]
@khiga8 Yup I can definitely add that!

**Review by broccolinisoup — COMMENTED** [review]
Sorry I missed this! Thanks for a new shiny rule 🤩 Only thing I would say is that we should add this rule to the README.md.

**Pull request merged**
